### ISSUE TITLE
Sharing initial motions

### ISSUE THREAD

**Issue by enesduran** [sanweiliti/RoHM#16]
Than you for the great work! 

When are you intending to share initial motions from regressors? The LEMO-based initial motion data requires permission for access, I sent a request but could not get a response. 

Thanks

**Comment by enesduran** [comment]
Thank you for updating initial motions. When I run the following comment ('''python test_prox_egobody.py --config=cfg_files/test_cfg/prox_rgb.yaml --recording_name=RECORDING_NAME''') for  evaluation with your initial motion values I get the following results. The keypoints seems fine but initial motion is off, maybe it needs a global alignment. Is it a problem on my end? Could you check? Best 
![s001_frame_00172__00 00 05 677](https://github.com/sanweiliti/RoHM/assets/48105487/c4c17f6c-976c-453e-b661-373976e7d4fb)
![s001_frame_00172__00 00 05 677](https://github.com/sanweiliti/RoHM/assets/48105487/36315ace-24cc-4a70-b88b-91512e05dd24)

**Comment by sanweiliti** [comment]
Thanks for the feedback, I will look into it. Could you specify which sequence did you test on?

**Comment by enesduran** [comment]
it was MPH1Library_00034_01

**Comment by sanweiliti** [comment]
Hi, I tested it on my side and the results seem to be correct. 
Not sure what caused the case in your image, for debugging purpose, I would suggest to visualize the init motions (it's in the same format as the original PROX seudo GT sequences) with original PROX dataset repo visualization script to see if they align with the image.

**Comment by enesduran** [comment]
Okay, thank you, I will try to visualize init motions with PROX vis code. 
One thing directly comes to my mind is: I used EGL backend for pyrender. Could it be the reason?

**Comment by sanweiliti** [comment]
hmm I'm not quite sure, you can disable the rendering and use the flag 'visualize' to visualize via Open3D, to see if the mesh/skeleton looks okay from the camera view.
