### ISSUE TITLE
Amass joint masks

### ISSUE THREAD

**Issue by EvelynFan** [sanweiliti/RoHM#17]
Hi, thanks for the great work! I noticed that the PROX joint masks are loaded in the posenet training script. But in the config yaml file, the dataset used is AMASS. Wondering which dataset should be used for training the posenet.

**Comment by sanweiliti** [comment]
Hi, 

The posenet is trained on AMASS dataset, yet we are loading the occlusion masks from PROX during training to mimic the real-life occlusion cases.

**Comment by EvelynFan** [comment]
Got it, thanks! One more question, how to handle the clip length which is longer than 145?

**Comment by EvelynFan** [comment]
> Got it, thanks! One more question, how to handle the clip length which is longer than 145?

If we split the video into multiple clips and feed them into the diffusion model,a postprocessing step may be required after concatenating all results?

**Comment by Dong09** [comment]
@sanweiliti i have the same question about clip length which is longer than 145. I would be grateful.
