### ISSUE TITLE
Question: does RoHM support multi-person tracking?

### ISSUE THREAD

**Issue by atonalfreerider** [sanweiliti/RoHM#2]
Very excited to try this. I have a research application involving partner dancers. I haven't seen anything else that can do good monocular 3D poses. If this supports multiple people, especially if they are standing close to each other, or occluding, this is a big advancement.

**Comment by sanweiliti** [comment]
Hi,

Unfotrunately we didn't include the multi-people tracking in this work. So far it only supports for single-person motion reconstruction.
