### ISSUE TITLE
about custom dataset

### ISSUE THREAD

**Issue by Dong09** [sanweiliti/RoHM#24]
Thanks for releasing such an outstanding work.
I have prepared the initial SMPL-X sequence according to the data format in ‘data/init_motions/init_prox_rgb’ and I have generated the mask_joint file with all 1's, other things such as: color.json only uses 'f' and 'c ' parameters, and the unit matrix used by cam2world. 
But I am getting very bad results, can you tell me the reason,i would be grateful , after visualization the results are shown below:

![IMG_20240821_165253.jpg](https://github.com/user-attachments/assets/5e4e662e-b2fe-479a-830e-7207800f7e1c)

**Comment by txOdyssey** [comment]
hi, I got similar bad results and have no idea what was wrong. I would be grateful if you let me know how you solved this problem. Thanks a lot!

**Comment by Dong09** [comment]
Hello, the reason I have this is because I did not have the z/y axis up and I changed the json of my **cam2world**.

I suggest you save the **test_batch_pose['motion_repr_noisy']** of your motions and the official motions in **test_prox_egobody.py** and vis them to see the specific directions.
