### ISSUE TITLE
Just wanted to cheer you on!

### ISSUE THREAD

**Issue by oliverban** [sanweiliti/RoHM#4]
Congrats to an amazing research effort guys and gals! This looks very cool and I can think of many implementations for this. I am looking forward to the code and being able to do this myself for mocap in 3D and VFX!

Question:
Will it be able to output an FBX/BVH or equivalent datastructure for transfer to other 3D programs?
Is it locked to camera-space or is it trying to capture the person in a "volume", meaning the mocap data is usable for showcasing other camera angles as well?

Again, thanks so much and very looking forward to it - genius!

**Comment by sanweiliti** [comment]
Hi,
Thanks for your interest in RoHM! The output is in joint positions, or SMPL-X model parameters. For the second question, I'm not sure if I understand you correctly, but the output is in a 3D global space, if you want to visualize from other camera angles you can just change the rendering camera view in the visualization scripts.
