### ISSUE TITLE
Where to get SMPL-X model 1.0?

### ISSUE THREAD

**Issue by carlosedubarreto** [sanweiliti/RoHM#7]
Hi, do you have a tip where we could get the SMPL-X model v 1.0?

I can only find version 1.1, thanks.

**Comment by carlosedubarreto** [comment]
I thin I've found the answer. looks like the smplx 1.1 has the smplx 1.0 .
At least it is what is written on the version.txt inside it 
![image](https://github.com/sanweiliti/RoHM/assets/4061130/4fdc09d8-6bf8-40fb-bfe2-ddc0e9df77f6)

**Comment by sanweiliti** [comment]
Great let me know if it does not work!

**Comment by carlosedubarreto** [comment]
Sorry, I had a problem on another part of the process. As I'm trying to run on windows, I'm having other problems.
I'll close this for now because I wont be able to test it further for now.
thanks for the attention
