### ISSUE TITLE
Running the code will result in an OOM error

### ISSUE THREAD

**Issue by YouTianlong** [sanweiliti/RoHM#9]
![2024-05-20 15-01-48屏幕截图](https://github.com/sanweiliti/RoHM/assets/11797662/26ef0fb4-5ede-495e-9c2f-32a71895a963)

Thanks!

**Comment by Xianqi-Zhang** [comment]
Reduce the value of `batch_size` in the corresponding file in cfg_files/xxx_cfg/xxx.yaml

**Comment by YouTianlong** [comment]
Thank you
